# Generated by Django 5.0.1 on 2024-01-16 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentApp', '0002_alter_comment_publisheddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publishedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
